### ISSUE TITLE
Dashes in front matter enable github preview

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/standards-docs#1]
Just noticed, pluses render like this:
<img width="990" alt="screen shot 2017-01-26 at 17 39 56" src="https://cloud.githubusercontent.com/assets/761444/22353455/9031e32c-e3ee-11e6-96a6-13ca1529f89e.png">

Dashes render like this:
<img width="296" alt="screen shot 2017-01-26 at 17 40 28" src="https://cloud.githubusercontent.com/assets/761444/22353470/9d7d4c6a-e3ee-11e6-9310-81c11737739e.png">

# 🤷 meh, nbd though

**Comment by karissademi** [comment]
That looks terrible. I'll switch to the minuses. Too bad, I was enjoying the positivity. +++
