### ISSUE TITLE
Eliminate need to include compiled JS in version control

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/standards-docs#2]
Ideally, compiling the javascript would be part of the overall build process (the same process that compiles the static pages).

Options:
1. Add the js build step to `.travis.yml` `scripts`. This would solve it for deploys, but you'd still need to do it manually while developing.
2. Research recommended approaches in hugo docs/community. Maybe there's a way to execute it when you run the `hugo` command. I'm sure other devs have faced this problem.

**Comment by karissademi** [comment]
This is also an issue with the compiled sass files. The solution should address both.

**Comment by karissademi** [comment]
This was addressed in 6b5002a296554fd80ed3e87169462a2ae39b9bc5.
