### ISSUE TITLE
What do you mean by remove font-awesome and iconicons?

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/standards-docs#4]
Great upgrade guide! Had a question: Why remove references to font-awesome and iconicons? Does the new standards not bundle those? By remove references, do you mean remove any `fa fa-trash` etc. used in elements? Or just the `<link>` tag importing the libraries?

**Comment by karissademi** [comment]
Good question. Font awesome is bundled, so you don't need to include it separately. We aren't using iconicons anymore. You should remove the `<link>` tag to those dependencies. 

I'll address this & once I return 🛬 (or feel free to make a PR).
